version: '3'

services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm start:dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - PROMETHEUS_PORT=9100
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:lts
    restart: always
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=somu
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=somi
      - MYSQL_PASSWORD=somi
      - MYSQL_TCP_PORT=3307
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8088:80'
    environment:
      - PMA_HOST=mysql_db
      - MYSQL_ROOT_PASSWORD=somu
    depends_on:
      - mysql_db
  prometheus:
    image: prom/prometheus
    ports:
      - '9095:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
