global:
  scrape_interval: 15s

scrape_configs:
  - job_name: nestjs-service
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - '192.168.0.118:3000'
